services:
  apache_tika:
    container_name: apache_tika
    build:
      context: ./../apache-tika-service
      dockerfile: Dockerfile
    ports:
      - "9998:9998"
    networks:
      - decide
    restart: unless-stopped

  pdf-content-service:
    container_name: pdf-content
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - decide
    environment:
      SEGMENTATION__API_KEY: "SECRET"
      LOG_LEVEL: "info"
      ALLOW_MU_AUTH_SUDO: true
      APACHE_TIKA_URL: "http://apache_tika:9998/tika"
      EXPECTED_TASK_PREDICATE: "http://www.w3.org/ns/adms#status"
      EXPECTED_TASK_OBJECT: "http://redpencil.data.gift/id/concept/JobStatus/scheduled"
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/publication
      MOUNTED_SHARE_FOLDER: "/mnt/share"
      CONFIG_PATH: /app/config.json
    volumes:
      - ./:/app
      - ./../app-decide/data/files:/mnt/share
      - ./config.json:/app/config.json:ro # Mount config as read-only

networks:
  decide:
    external: true
